# remote_theme: just-the-docs/just-the-docs
remote_theme: sighingnow/jekyll-gitbook
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
header_pages:
  - impressum.md
